[project]
name = "brfss"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.2",
    "pandas>=2.2.3",
    "polars>=1.11.0",
    "pyarrow>=17.0.0",
]
